version: '3.8'
services:
  photo-samples_app:
    image: docker-run-slotegrator
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        LOCAL: '1'
    container_name: docker-run-slotegrator.dev
    ports:
      - "80:8080"
    environment:
      PORT: '8080'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      DB_HOST: "${DB_HOST}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      CLOUDSQL_INSTANCE: "${CLOUDSQL_INSTANCE}"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./src/:/var/www/html/
      - ./secrets/:/var/www/.secrets/