openapi: 3.0.0
info:
  version: '0.0.1'
  title: 'SG'
servers:
  - url: 'sg.putsko.com.ua'
paths:
  /user/{id}:
    get:
      summary: 'Returns details about a particular user'
      operationId: listUser
      security:
        - bearerAuth: []
      tags:
        - user
      parameters:
        - name: id
          in: path
          description: ID of the user
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Details about a user by ID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
            $ref: '#/components/responses/UnauthorizedError'
components:
  schemas:
    User:
        type: object
        required:
            - id
            - name
            - email
        properties:
            id:
                type: integer
                format: int64
            name:
                type: string
            email:
                type: string
    Error:
        type: object
        required:
            - code
            - message
        properties:
            code:
                type: integer
                format: int32
            message:
                type: string
    UnauthorizedError:
        type: object
        required:
            - type
            - code
            - message
        properties:
            type:
                type: string
            code:
                type: integer
                format: int32
            message:
                type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []